<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
    <!-- VSIX settings -->
    <VSSDKBuildToolsAutoSetup>true</VSSDKBuildToolsAutoSetup>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <UseWPF>true</UseWPF>
    <CopyBuildOutputToOutputDirectory>true</CopyBuildOutputToOutputDirectory>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="OllamaAgentToolWindowControl.xaml" />
    <None Remove="Resources\Fonts\Font Awesome 7 Brands-Regular-400.otf" />
    <None Remove="Resources\Fonts\Font Awesome 7 Free-Regular-400.otf" />
    <None Remove="Resources\Fonts\Font Awesome 7 Free-Solid-900.otf" />
    <None Remove="Resources\Fonts\icomoon.ttf" />
    <None Remove="Resources\Images\IconImages\clock-rotate-left-solid.png" />
    <None Remove="Resources\Images\IconImages\gear-solid.png" />
    <None Remove="Resources\Images\IconImages\gears-solid.png" />
    <None Remove="Resources\Images\IconImages\message-add-solid.png" />
    <None Remove="Resources\Images\IconImages\message-remove-solid.png" />
    <None Remove="Resources\Images\IconImages\paper-plane-solid.png" />
    <None Remove="Resources\Images\IconImages\rotate-solid.png" />
    <None Remove="Resources\Images\IconImages\rotate-solid2.png" />
    <None Remove="Resources\Images\IconImages\screwdriver-wrench-solid.png" />
  </ItemGroup>
  <ItemGroup>
    <VSCTCompile Include="OllamaAgent.vsct">
      <ResourceName>Menus.ctmenu</ResourceName>
    </VSCTCompile>
  </ItemGroup>
  <ItemGroup>
    <Content Include="$(IntermediateOutputPath)OllamaAgent.cto">
      <Link>Menus.ctmenu</Link>
      <IncludeInVSIX>true</IncludeInVSIX>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectCapability Include="CreateVsixContainer" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Community.VisualStudio.Toolkit.17" Version="17.0.551" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.14.40265" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="18.5.40034" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Xaml" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Fonts\Font Awesome 7 Brands-Regular-400.otf" />
    <Resource Include="Resources\Fonts\Font Awesome 7 Free-Regular-400.otf" />
    <Resource Include="Resources\Fonts\Font Awesome 7 Free-Solid-900.otf" />
    <Resource Include="Resources\Fonts\icomoon.ttf" />
    <Resource Include="Resources\Images\IconImages\clock-rotate-left-solid.png" />
    <Resource Include="Resources\Images\IconImages\gear-solid.png" />
    <Resource Include="Resources\Images\IconImages\gears-solid.png" />
    <Resource Include="Resources\Images\IconImages\message-add-solid.png" />
    <Resource Include="Resources\Images\IconImages\message-remove-solid.png" />
    <Resource Include="Resources\Images\IconImages\paper-plane-solid.png" />
    <Resource Include="Resources\Images\IconImages\rotate-solid.png" />
    <Resource Include="Resources\Images\IconImages\rotate-solid2.png" />
    <Resource Include="Resources\Images\IconImages\screwdriver-wrench-solid.png" />
  </ItemGroup>
</Project>